### ISSUE TITLE
Reminders to update

### ISSUE THREAD

**Issue by 04alband** [ContextKeeper/ContextKeeper.VisualStudio#5] opened 2023-05-07 09:37 UTC
![image](https://user-images.githubusercontent.com/30078018/236669418-1d3c84af-abaf-49a1-b22c-50fcc48daa42.png)
This is not cool. I'm going to have to OK each one of these, each one opening the download site in a new tab. We get this reminder when VS opens, but it also seems per Windows login? Or maybe it's computer wake?

I like the extension, no complaints there. I downloaded the update when I got the first reminder and I want to install it, I'm just in the middle of various coding sessions and haven't had an opportunity to restart all my VS instances.

A reminder every time VS starts seems sufficient/reasonable. More than that is actually getting quite annoying now.

Many thanks for the useful extension, just please dial down the reminders.

P.S. yeah, that background looks pretty weird/funny

**Comment by PiotrKarczmarz** [comment] 2023-05-09 12:16
It is clearly a bug and not intended behavior 😀 The reminder dialog should open only once when a solution is fully loaded. After a certain delay, it may open again, but definitely it shouldn't be opened multiple times.

I will investigate why it is happening and prepare a fix. Also I will try to find a good solution to show the reminder dialog only once,, regardless how many VS instances are already opened. This should remove/minimize annoyance factor.


P. S. The background picture is really funny, thanks for posting it 😉

**Comment by PiotrKarczmarz** [comment] 2023-07-18 13:19
It was fixed in the version [1.98.2](https://contextkeeper.io/blog/downloads/#v1.98.2)

**Closed by PiotrKarczmarz** 2023-07-18 13:19 UTC
